/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum BtApiVersion {
    #[serde(rename = "UNDEFINED")]
    Undefined,
    #[serde(rename = "V1_START")]
    V1Start,
    #[serde(rename = "V2_SERIALIZATION_UNIFICATION")]
    V2SerializationUnification,
    #[serde(rename = "V3_NEW_BOM_FORMAT")]
    V3NewBomFormat,
    #[serde(rename = "V4_TRANSACTIONS_NO_NEW")]
    V4TransactionsNoNew,
    #[serde(rename = "V5_BODY_DETAILS_COMPOSITE_REFERENCE")]
    V5BodyDetailsCompositeReference,
    #[serde(rename = "V6_JSON_EDIT_RESPONSE_BUGFIX")]
    V6JsonEditResponseBugfix,
    #[serde(rename = "V7_SKETCH_ENDPOINT_INCLUDES_SOLVE_STATUS")]
    V7SketchEndpointIncludesSolveStatus,
    #[serde(rename = "V8_RESTORE_NOOP_NO_NEW_MICROVERSION")]
    V8RestoreNoopNoNewMicroversion,
    #[serde(rename = "V9_INCLUDE_DETERMINISTIC_IDS_TO_QUERY_RESPONSES")]
    V9IncludeDeterministicIdsToQueryResponses,
    #[serde(rename = "V10_VALIDATE_VISIBILTY_CONDITIONS_FOR_PS_CONFIG_PARAMS")]
    V10ValidateVisibiltyConditionsForPsConfigParams,

}

impl std::fmt::Display for BtApiVersion {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Undefined => write!(f, "UNDEFINED"),
            Self::V1Start => write!(f, "V1_START"),
            Self::V2SerializationUnification => write!(f, "V2_SERIALIZATION_UNIFICATION"),
            Self::V3NewBomFormat => write!(f, "V3_NEW_BOM_FORMAT"),
            Self::V4TransactionsNoNew => write!(f, "V4_TRANSACTIONS_NO_NEW"),
            Self::V5BodyDetailsCompositeReference => write!(f, "V5_BODY_DETAILS_COMPOSITE_REFERENCE"),
            Self::V6JsonEditResponseBugfix => write!(f, "V6_JSON_EDIT_RESPONSE_BUGFIX"),
            Self::V7SketchEndpointIncludesSolveStatus => write!(f, "V7_SKETCH_ENDPOINT_INCLUDES_SOLVE_STATUS"),
            Self::V8RestoreNoopNoNewMicroversion => write!(f, "V8_RESTORE_NOOP_NO_NEW_MICROVERSION"),
            Self::V9IncludeDeterministicIdsToQueryResponses => write!(f, "V9_INCLUDE_DETERMINISTIC_IDS_TO_QUERY_RESPONSES"),
            Self::V10ValidateVisibiltyConditionsForPsConfigParams => write!(f, "V10_VALIDATE_VISIBILTY_CONDITIONS_FOR_PS_CONFIG_PARAMS"),
        }
    }
}

impl Default for BtApiVersion {
    fn default() -> BtApiVersion {
        Self::Undefined
    }
}

