/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtAssemblySimulationTable3236 {
    /// Type of JSON object.
    #[serde(rename = "btType", skip_serializing_if = "Option::is_none")]
    pub bt_type: Option<String>,
    #[serde(rename = "allRowValues", skip_serializing_if = "Option::is_none")]
    pub all_row_values: Option<Vec<Vec<String>>>,
    #[serde(rename = "columnCount", skip_serializing_if = "Option::is_none")]
    pub column_count: Option<i32>,
    #[serde(rename = "frozenColumns", skip_serializing_if = "Option::is_none")]
    pub frozen_columns: Option<i32>,
    #[serde(rename = "isFailed", skip_serializing_if = "Option::is_none")]
    pub is_failed: Option<bool>,
    #[serde(rename = "nodeId", skip_serializing_if = "Option::is_none")]
    pub node_id: Option<String>,
    #[serde(rename = "readOnly", skip_serializing_if = "Option::is_none")]
    pub read_only: Option<bool>,
    #[serde(rename = "rowCount", skip_serializing_if = "Option::is_none")]
    pub row_count: Option<i32>,
    #[serde(rename = "sortOrder", skip_serializing_if = "Option::is_none")]
    pub sort_order: Option<Box<models::BtTableSortOrder4371>>,
    #[serde(rename = "tableColumns", skip_serializing_if = "Option::is_none")]
    pub table_columns: Option<Vec<models::BtTableColumnInfo1222>>,
    #[serde(rename = "tableId", skip_serializing_if = "Option::is_none")]
    pub table_id: Option<String>,
    #[serde(rename = "tableRows", skip_serializing_if = "Option::is_none")]
    pub table_rows: Option<Vec<models::BtTableRow1054>>,
    #[serde(rename = "title", skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl BtAssemblySimulationTable3236 {
    pub fn new() -> BtAssemblySimulationTable3236 {
        BtAssemblySimulationTable3236 {
            bt_type: None,
            all_row_values: None,
            column_count: None,
            frozen_columns: None,
            is_failed: None,
            node_id: None,
            read_only: None,
            row_count: None,
            sort_order: None,
            table_columns: None,
            table_id: None,
            table_rows: None,
            title: None,
        }
    }
}

