/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtBillOfMaterialsItemSourceInfo {
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<String>,
    #[serde(rename = "documentId", skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
    #[serde(rename = "elementId", skip_serializing_if = "Option::is_none")]
    pub element_id: Option<String>,
    #[serde(rename = "fullConfiguration", skip_serializing_if = "Option::is_none")]
    pub full_configuration: Option<String>,
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    #[serde(rename = "isStandardContent", skip_serializing_if = "Option::is_none")]
    pub is_standard_content: Option<bool>,
    #[serde(rename = "nonGeometricItemId", skip_serializing_if = "Option::is_none")]
    pub non_geometric_item_id: Option<String>,
    #[serde(rename = "partId", skip_serializing_if = "Option::is_none")]
    pub part_id: Option<String>,
    #[serde(rename = "sourceElementMicroversionId", skip_serializing_if = "Option::is_none")]
    pub source_element_microversion_id: Option<String>,
    #[serde(rename = "thumbnailInfo", skip_serializing_if = "Option::is_none")]
    pub thumbnail_info: Option<Box<models::BtThumbnailInfo>>,
    #[serde(rename = "versionMetadataWorkspaceMicroversionId", skip_serializing_if = "Option::is_none")]
    pub version_metadata_workspace_microversion_id: Option<String>,
    #[serde(rename = "viewHref", skip_serializing_if = "Option::is_none")]
    pub view_href: Option<String>,
    #[serde(rename = "wvmId", skip_serializing_if = "Option::is_none")]
    pub wvm_id: Option<String>,
    #[serde(rename = "wvmType", skip_serializing_if = "Option::is_none")]
    pub wvm_type: Option<String>,
}

impl BtBillOfMaterialsItemSourceInfo {
    pub fn new() -> BtBillOfMaterialsItemSourceInfo {
        BtBillOfMaterialsItemSourceInfo {
            configuration: None,
            document_id: None,
            element_id: None,
            full_configuration: None,
            href: None,
            is_standard_content: None,
            non_geometric_item_id: None,
            part_id: None,
            source_element_microversion_id: None,
            thumbnail_info: None,
            version_metadata_workspace_microversion_id: None,
            view_href: None,
            wvm_id: None,
            wvm_type: None,
        }
    }
}

