/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "btType")]
pub enum BtBaseEntityData33 {
    #[serde(rename="BTEntityDeletion-24")]
    BtEntityDeletion24 {
        #[serde(rename = "constructionPlane", skip_serializing_if = "Option::is_none")]
        construction_plane: Option<bool>,
        #[serde(rename = "copyWithoutGeometry", skip_serializing_if = "Option::is_none")]
        copy_without_geometry: Option<Box<models::BtBaseEntityData33>>,
        #[serde(rename = "decompressed", skip_serializing_if = "Option::is_none")]
        decompressed: Option<Box<models::BtBaseEntityData33>>,
        #[serde(rename = "defaultPane", skip_serializing_if = "Option::is_none")]
        default_pane: Option<bool>,
        #[serde(rename = "deletion", skip_serializing_if = "Option::is_none")]
        deletion: Option<bool>,
        #[serde(rename = "featureIds", skip_serializing_if = "Option::is_none")]
        feature_ids: Option<Vec<String>>,
        #[serde(rename = "fromSketch", skip_serializing_if = "Option::is_none")]
        from_sketch: Option<bool>,
        #[serde(rename = "geometries", skip_serializing_if = "Option::is_none")]
        geometries: Option<Vec<models::BtEntityGeometry35>>,
        #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
        origin: Option<bool>,
    },
    #[serde(rename="BTFeatureEntity-34")]
    BtFeatureEntity34 {
        #[serde(rename = "constructionPlane", skip_serializing_if = "Option::is_none")]
        construction_plane: Option<bool>,
        #[serde(rename = "copyWithoutGeometry", skip_serializing_if = "Option::is_none")]
        copy_without_geometry: Option<Box<models::BtBaseEntityData33>>,
        #[serde(rename = "decompressed", skip_serializing_if = "Option::is_none")]
        decompressed: Option<Box<models::BtBaseEntityData33>>,
        #[serde(rename = "defaultPane", skip_serializing_if = "Option::is_none")]
        default_pane: Option<bool>,
        #[serde(rename = "deletion", skip_serializing_if = "Option::is_none")]
        deletion: Option<bool>,
        #[serde(rename = "featureIds", skip_serializing_if = "Option::is_none")]
        feature_ids: Option<Vec<String>>,
        #[serde(rename = "fromSketch", skip_serializing_if = "Option::is_none")]
        from_sketch: Option<bool>,
        #[serde(rename = "geometries", skip_serializing_if = "Option::is_none")]
        geometries: Option<Vec<models::BtEntityGeometry35>>,
        #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
        origin: Option<bool>,
    },
}

impl Default for BtBaseEntityData33 {
    fn default() -> Self {
        Self::BtEntityDeletion24 {
            construction_plane: Default::default(),
            copy_without_geometry: Default::default(),
            decompressed: Default::default(),
            default_pane: Default::default(),
            deletion: Default::default(),
            feature_ids: Default::default(),
            from_sketch: Default::default(),
            geometries: Default::default(),
            origin: Default::default(),
        }
        
    }
}


