/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtCategoryPropertyConfigInfo {
    #[serde(rename = "computedAssemblyPropertyAggregatedPropertyId", skip_serializing_if = "Option::is_none")]
    pub computed_assembly_property_aggregated_property_id: Option<String>,
    #[serde(rename = "computedAssemblyPropertyAggregationOperator", skip_serializing_if = "Option::is_none")]
    pub computed_assembly_property_aggregation_operator: Option<i32>,
    #[serde(rename = "computedAssemblyPropertyConfig", skip_serializing_if = "Option::is_none")]
    pub computed_assembly_property_config: Option<Box<models::BtComputedAssemblyPropertyConfig>>,
    #[serde(rename = "computedAssemblyPropertyErrorValuePolicy", skip_serializing_if = "Option::is_none")]
    pub computed_assembly_property_error_value_policy: Option<i32>,
    #[serde(rename = "computedAssemblyPropertyFilterInverted", skip_serializing_if = "Option::is_none")]
    pub computed_assembly_property_filter_inverted: Option<bool>,
    #[serde(rename = "computedAssemblyPropertyFilterPropertyId", skip_serializing_if = "Option::is_none")]
    pub computed_assembly_property_filter_property_id: Option<String>,
    #[serde(rename = "computedAssemblyPropertyMissingValuePolicy", skip_serializing_if = "Option::is_none")]
    pub computed_assembly_property_missing_value_policy: Option<i32>,
    #[serde(rename = "computedAssemblyPropertySecondaryPropertyId", skip_serializing_if = "Option::is_none")]
    pub computed_assembly_property_secondary_property_id: Option<String>,
    #[serde(rename = "computedPartPropertyConfig", skip_serializing_if = "Option::is_none")]
    pub computed_part_property_config: Option<Box<models::BtComputedPartPropertyConfig>>,
    #[serde(rename = "computedPropertyFunctionName", skip_serializing_if = "Option::is_none")]
    pub computed_property_function_name: Option<String>,
    #[serde(rename = "computedPropertyFunctionNamespace", skip_serializing_if = "Option::is_none")]
    pub computed_property_function_namespace: Option<String>,
    #[serde(rename = "computedPropertyFunctionURL", skip_serializing_if = "Option::is_none")]
    pub computed_property_function_url: Option<String>,
    #[serde(rename = "defaultValue", skip_serializing_if = "Option::is_none")]
    pub default_value: Option<String>,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "enumValues", skip_serializing_if = "Option::is_none")]
    pub enum_values: Option<Vec<models::BtMetadataEnumValue>>,
    #[serde(rename = "maxCount", skip_serializing_if = "Option::is_none")]
    pub max_count: Option<i32>,
    #[serde(rename = "maxDate", skip_serializing_if = "Option::is_none")]
    pub max_date: Option<String>,
    #[serde(rename = "maxLength", skip_serializing_if = "Option::is_none")]
    pub max_length: Option<i32>,
    #[serde(rename = "maxValue", skip_serializing_if = "Option::is_none")]
    pub max_value: Option<f64>,
    #[serde(rename = "minCount", skip_serializing_if = "Option::is_none")]
    pub min_count: Option<i32>,
    #[serde(rename = "minDate", skip_serializing_if = "Option::is_none")]
    pub min_date: Option<String>,
    #[serde(rename = "minLength", skip_serializing_if = "Option::is_none")]
    pub min_length: Option<i32>,
    #[serde(rename = "minValue", skip_serializing_if = "Option::is_none")]
    pub min_value: Option<f64>,
    #[serde(rename = "multiline", skip_serializing_if = "Option::is_none")]
    pub multiline: Option<bool>,
    #[serde(rename = "multivalued", skip_serializing_if = "Option::is_none")]
    pub multivalued: Option<bool>,
    #[serde(rename = "pattern", skip_serializing_if = "Option::is_none")]
    pub pattern: Option<String>,
    #[serde(rename = "publishState", skip_serializing_if = "Option::is_none")]
    pub publish_state: Option<i32>,
    #[serde(rename = "quantityType", skip_serializing_if = "Option::is_none")]
    pub quantity_type: Option<i32>,
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
}

impl BtCategoryPropertyConfigInfo {
    pub fn new() -> BtCategoryPropertyConfigInfo {
        BtCategoryPropertyConfigInfo {
            computed_assembly_property_aggregated_property_id: None,
            computed_assembly_property_aggregation_operator: None,
            computed_assembly_property_config: None,
            computed_assembly_property_error_value_policy: None,
            computed_assembly_property_filter_inverted: None,
            computed_assembly_property_filter_property_id: None,
            computed_assembly_property_missing_value_policy: None,
            computed_assembly_property_secondary_property_id: None,
            computed_part_property_config: None,
            computed_property_function_name: None,
            computed_property_function_namespace: None,
            computed_property_function_url: None,
            default_value: None,
            display_name: None,
            enum_values: None,
            max_count: None,
            max_date: None,
            max_length: None,
            max_value: None,
            min_count: None,
            min_date: None,
            min_length: None,
            min_value: None,
            multiline: None,
            multivalued: None,
            pattern: None,
            publish_state: None,
            quantity_type: None,
            required: None,
        }
    }
}

