/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "btType")]
pub enum BtConfiguredValuesColumnInfo1025 {
    #[serde(rename="BTConfiguredDimensionColumnInfo-2168")]
    BtConfiguredDimensionColumnInfo2168 {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "nodeId", skip_serializing_if = "Option::is_none")]
        node_id: Option<String>,
        #[serde(rename = "specification", skip_serializing_if = "Option::is_none")]
        specification: Option<Box<models::BtTableColumnSpec1967>>,
        #[serde(rename = "parentId", skip_serializing_if = "Option::is_none")]
        parent_id: Option<String>,
        #[serde(rename = "parentName", skip_serializing_if = "Option::is_none")]
        parent_name: Option<String>,
        #[serde(rename = "parentType", skip_serializing_if = "Option::is_none")]
        parent_type: Option<models::GbtConfiguredParentType>,
    },
    #[serde(rename="BTConfiguredFeatureColumnInfo-1014")]
    BtConfiguredFeatureColumnInfo1014 {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "nodeId", skip_serializing_if = "Option::is_none")]
        node_id: Option<String>,
        #[serde(rename = "specification", skip_serializing_if = "Option::is_none")]
        specification: Option<Box<models::BtTableColumnSpec1967>>,
        #[serde(rename = "parentId", skip_serializing_if = "Option::is_none")]
        parent_id: Option<String>,
        #[serde(rename = "parentName", skip_serializing_if = "Option::is_none")]
        parent_name: Option<String>,
        #[serde(rename = "parentType", skip_serializing_if = "Option::is_none")]
        parent_type: Option<models::GbtConfiguredParentType>,
    },
    #[serde(rename="BTConfiguredParameterColumnInfo-2900")]
    BtConfiguredParameterColumnInfo2900 {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "nodeId", skip_serializing_if = "Option::is_none")]
        node_id: Option<String>,
        #[serde(rename = "specification", skip_serializing_if = "Option::is_none")]
        specification: Option<Box<models::BtTableColumnSpec1967>>,
        #[serde(rename = "parentId", skip_serializing_if = "Option::is_none")]
        parent_id: Option<String>,
        #[serde(rename = "parentName", skip_serializing_if = "Option::is_none")]
        parent_name: Option<String>,
        #[serde(rename = "parentType", skip_serializing_if = "Option::is_none")]
        parent_type: Option<models::GbtConfiguredParentType>,
    },
    #[serde(rename="BTConfiguredSuppressionColumnInfo-2498")]
    BtConfiguredSuppressionColumnInfo2498 {
        #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
        id: Option<String>,
        #[serde(rename = "nodeId", skip_serializing_if = "Option::is_none")]
        node_id: Option<String>,
        #[serde(rename = "specification", skip_serializing_if = "Option::is_none")]
        specification: Option<Box<models::BtTableColumnSpec1967>>,
        #[serde(rename = "parentId", skip_serializing_if = "Option::is_none")]
        parent_id: Option<String>,
        #[serde(rename = "parentName", skip_serializing_if = "Option::is_none")]
        parent_name: Option<String>,
        #[serde(rename = "parentType", skip_serializing_if = "Option::is_none")]
        parent_type: Option<models::GbtConfiguredParentType>,
    },
}

impl Default for BtConfiguredValuesColumnInfo1025 {
    fn default() -> Self {
        Self::BtConfiguredDimensionColumnInfo2168 {
            id: Default::default(),
            node_id: Default::default(),
            specification: Default::default(),
            parent_id: Default::default(),
            parent_name: Default::default(),
            parent_type: Default::default(),
        }
        
    }
}


