/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtCompanyUserParams {
    /// Indicates the user is an admin if true.
    #[serde(rename = "admin", skip_serializing_if = "Option::is_none")]
    pub admin: Option<bool>,
    /// Company ID of the user.
    #[serde(rename = "companyId", skip_serializing_if = "Option::is_none")]
    pub company_id: Option<String>,
    /// String to override documentation name.
    #[serde(rename = "documentationNameOverride", skip_serializing_if = "Option::is_none")]
    pub documentation_name_override: Option<String>,
    /// Email ID of the company user.
    #[serde(rename = "email", skip_serializing_if = "Option::is_none")]
    pub email: Option<String>,
    /// List of global permissions to grant.
    #[serde(rename = "globalPermissions", skip_serializing_if = "Option::is_none")]
    pub global_permissions: Option<Vec<i32>>,
    /// Indicates the user is a guest user if true.
    #[serde(rename = "guest", skip_serializing_if = "Option::is_none")]
    pub guest: Option<bool>,
    /// Indicates the user is a light user if true.
    #[serde(rename = "light", skip_serializing_if = "Option::is_none")]
    pub light: Option<bool>,
}

impl BtCompanyUserParams {
    pub fn new() -> BtCompanyUserParams {
        BtCompanyUserParams {
            admin: None,
            company_id: None,
            documentation_name_override: None,
            email: None,
            global_permissions: None,
            guest: None,
            light: None,
        }
    }
}

