/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtDocumentSummarySearchInfo {
    #[serde(rename = "canMove", skip_serializing_if = "Option::is_none")]
    pub can_move: Option<bool>,
    #[serde(rename = "createdAt", skip_serializing_if = "Option::is_none")]
    pub created_at: Option<String>,
    #[serde(rename = "createdBy", skip_serializing_if = "Option::is_none")]
    pub created_by: Option<Box<models::BtUserBasicSummaryInfo>>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// URI to fetch complete information of the resource.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    /// Id of the resource.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "isContainer", skip_serializing_if = "Option::is_none")]
    pub is_container: Option<bool>,
    #[serde(rename = "isEnterpriseOwned", skip_serializing_if = "Option::is_none")]
    pub is_enterprise_owned: Option<bool>,
    #[serde(rename = "isMutable", skip_serializing_if = "Option::is_none")]
    pub is_mutable: Option<bool>,
    #[serde(rename = "jsonType")]
    pub json_type: String,
    #[serde(rename = "modifiedAt", skip_serializing_if = "Option::is_none")]
    pub modified_at: Option<String>,
    #[serde(rename = "modifiedBy", skip_serializing_if = "Option::is_none")]
    pub modified_by: Option<Box<models::BtUserBasicSummaryInfo>>,
    /// Name of the resource.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "owner", skip_serializing_if = "Option::is_none")]
    pub owner: Option<Box<models::BtOwnerInfo>>,
    #[serde(rename = "projectId", skip_serializing_if = "Option::is_none")]
    pub project_id: Option<String>,
    #[serde(rename = "resourceType", skip_serializing_if = "Option::is_none")]
    pub resource_type: Option<String>,
    #[serde(rename = "treeHref", skip_serializing_if = "Option::is_none")]
    pub tree_href: Option<String>,
    #[serde(rename = "unparentHref", skip_serializing_if = "Option::is_none")]
    pub unparent_href: Option<String>,
    /// URI to visualize the resource in a webclient if applicable.
    #[serde(rename = "viewRef", skip_serializing_if = "Option::is_none")]
    pub view_ref: Option<String>,
    #[serde(rename = "anonymousAccessAllowed", skip_serializing_if = "Option::is_none")]
    pub anonymous_access_allowed: Option<bool>,
    #[serde(rename = "anonymousAllowsExport", skip_serializing_if = "Option::is_none")]
    pub anonymous_allows_export: Option<bool>,
    #[serde(rename = "canUnshare", skip_serializing_if = "Option::is_none")]
    pub can_unshare: Option<bool>,
    #[serde(rename = "createdWithEducationPlan", skip_serializing_if = "Option::is_none")]
    pub created_with_education_plan: Option<bool>,
    #[serde(rename = "defaultElementId", skip_serializing_if = "Option::is_none")]
    pub default_element_id: Option<String>,
    #[serde(rename = "defaultVersionGraphMode", skip_serializing_if = "Option::is_none")]
    pub default_version_graph_mode: Option<models::BtVersionGraphMode>,
    #[serde(rename = "defaultVersionGraphShowAutoVersions", skip_serializing_if = "Option::is_none")]
    pub default_version_graph_show_auto_versions: Option<bool>,
    #[serde(rename = "defaultVersionGraphShowMerges", skip_serializing_if = "Option::is_none")]
    pub default_version_graph_show_merges: Option<bool>,
    #[serde(rename = "defaultWorkspace", skip_serializing_if = "Option::is_none")]
    pub default_workspace: Option<Box<models::BtWorkspaceInfo>>,
    #[serde(rename = "documentLabels", skip_serializing_if = "Option::is_none")]
    pub document_labels: Option<Vec<models::BtDocumentLabelInfo>>,
    #[serde(rename = "documentType", skip_serializing_if = "Option::is_none")]
    pub document_type: Option<i32>,
    #[serde(rename = "forceExportRules", skip_serializing_if = "Option::is_none")]
    pub force_export_rules: Option<bool>,
    #[serde(rename = "hasReleaseRevisionableObjects", skip_serializing_if = "Option::is_none")]
    pub has_release_revisionable_objects: Option<bool>,
    #[serde(rename = "hasRelevantInsertables", skip_serializing_if = "Option::is_none")]
    pub has_relevant_insertables: Option<bool>,
    #[serde(rename = "isOrphaned", skip_serializing_if = "Option::is_none")]
    pub is_orphaned: Option<bool>,
    #[serde(rename = "isUsingManagedWorkflow", skip_serializing_if = "Option::is_none")]
    pub is_using_managed_workflow: Option<bool>,
    #[serde(rename = "likedByCurrentUser", skip_serializing_if = "Option::is_none")]
    pub liked_by_current_user: Option<bool>,
    #[serde(rename = "likes", skip_serializing_if = "Option::is_none")]
    pub likes: Option<i64>,
    #[serde(rename = "notRevisionManaged", skip_serializing_if = "Option::is_none")]
    pub not_revision_managed: Option<bool>,
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[serde(rename = "numberOfTimesCopied", skip_serializing_if = "Option::is_none")]
    pub number_of_times_copied: Option<i64>,
    #[serde(rename = "numberOfTimesReferenced", skip_serializing_if = "Option::is_none")]
    pub number_of_times_referenced: Option<i64>,
    #[serde(rename = "parentId", skip_serializing_if = "Option::is_none")]
    pub parent_id: Option<String>,
    #[serde(rename = "permission", skip_serializing_if = "Option::is_none")]
    pub permission: Option<models::BtOldPermission>,
    #[serde(rename = "permissionSet", skip_serializing_if = "Option::is_none")]
    pub permission_set: Option<Vec<String>>,
    #[serde(rename = "public", skip_serializing_if = "Option::is_none")]
    pub public: Option<bool>,
    #[serde(rename = "publishedVersionId", skip_serializing_if = "Option::is_none")]
    pub published_version_id: Option<String>,
    #[serde(rename = "recentVersion", skip_serializing_if = "Option::is_none")]
    pub recent_version: Option<Box<models::BtBaseInfo>>,
    #[serde(rename = "sequence", skip_serializing_if = "Option::is_none")]
    pub sequence: Option<String>,
    #[serde(rename = "supportTeamUserAndShared", skip_serializing_if = "Option::is_none")]
    pub support_team_user_and_shared: Option<bool>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(rename = "thumbnail", skip_serializing_if = "Option::is_none")]
    pub thumbnail: Option<Box<models::BtThumbnailInfo>>,
    #[serde(rename = "totalWorkspacesScheduledForUpdate", skip_serializing_if = "Option::is_none")]
    pub total_workspaces_scheduled_for_update: Option<i32>,
    #[serde(rename = "totalWorkspacesUpdating", skip_serializing_if = "Option::is_none")]
    pub total_workspaces_updating: Option<i32>,
    #[serde(rename = "trash", skip_serializing_if = "Option::is_none")]
    pub trash: Option<bool>,
    #[serde(rename = "trashedAt", skip_serializing_if = "Option::is_none")]
    pub trashed_at: Option<String>,
    #[serde(rename = "userAccountLimitsBreached", skip_serializing_if = "Option::is_none")]
    pub user_account_limits_breached: Option<bool>,
    #[serde(rename = "searchHits", skip_serializing_if = "Option::is_none")]
    pub search_hits: Option<Vec<models::BtDocumentSearchHitInfo>>,
}

impl BtDocumentSummarySearchInfo {
    pub fn new(json_type: String) -> BtDocumentSummarySearchInfo {
        BtDocumentSummarySearchInfo {
            can_move: None,
            created_at: None,
            created_by: None,
            description: None,
            href: None,
            id: None,
            is_container: None,
            is_enterprise_owned: None,
            is_mutable: None,
            json_type,
            modified_at: None,
            modified_by: None,
            name: None,
            owner: None,
            project_id: None,
            resource_type: None,
            tree_href: None,
            unparent_href: None,
            view_ref: None,
            anonymous_access_allowed: None,
            anonymous_allows_export: None,
            can_unshare: None,
            created_with_education_plan: None,
            default_element_id: None,
            default_version_graph_mode: None,
            default_version_graph_show_auto_versions: None,
            default_version_graph_show_merges: None,
            default_workspace: None,
            document_labels: None,
            document_type: None,
            force_export_rules: None,
            has_release_revisionable_objects: None,
            has_relevant_insertables: None,
            is_orphaned: None,
            is_using_managed_workflow: None,
            liked_by_current_user: None,
            likes: None,
            not_revision_managed: None,
            notes: None,
            number_of_times_copied: None,
            number_of_times_referenced: None,
            parent_id: None,
            permission: None,
            permission_set: None,
            public: None,
            published_version_id: None,
            recent_version: None,
            sequence: None,
            support_team_user_and_shared: None,
            tags: None,
            thumbnail: None,
            total_workspaces_scheduled_for_update: None,
            total_workspaces_updating: None,
            trash: None,
            trashed_at: None,
            user_account_limits_breached: None,
            search_hits: None,
        }
    }
}

