/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtInsertablesListResponse {
    #[serde(rename = "canSaveVersion", skip_serializing_if = "Option::is_none")]
    pub can_save_version: Option<bool>,
    #[serde(rename = "changesSinceVersionSave", skip_serializing_if = "Option::is_none")]
    pub changes_since_version_save: Option<i32>,
    #[serde(rename = "configuration", skip_serializing_if = "Option::is_none")]
    pub configuration: Option<std::collections::HashMap<String, models::BtfsValue1888>>,
    #[serde(rename = "configurationKey", skip_serializing_if = "Option::is_none")]
    pub configuration_key: Option<String>,
    #[serde(rename = "hasMultipleVersions", skip_serializing_if = "Option::is_none")]
    pub has_multiple_versions: Option<bool>,
    /// URI for current page of resources.
    #[serde(rename = "href", skip_serializing_if = "Option::is_none")]
    pub href: Option<String>,
    /// Array of items in the current page.
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<models::BtInsertableInfo>>,
    /// URI for next page of the resources if more are available.
    #[serde(rename = "next", skip_serializing_if = "Option::is_none")]
    pub next: Option<String>,
    /// URI for previous page of the resources.
    #[serde(rename = "previous", skip_serializing_if = "Option::is_none")]
    pub previous: Option<String>,
    #[serde(rename = "updatedThumbnailUri", skip_serializing_if = "Option::is_none")]
    pub updated_thumbnail_uri: Option<String>,
}

impl BtInsertablesListResponse {
    pub fn new() -> BtInsertablesListResponse {
        BtInsertablesListResponse {
            can_save_version: None,
            changes_since_version_save: None,
            configuration: None,
            configuration_key: None,
            has_multiple_versions: None,
            href: None,
            items: None,
            next: None,
            previous: None,
            updated_thumbnail_uri: None,
        }
    }
}

