/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtInspectionTableRowMetadata2485 {
    /// Type of JSON object.
    #[serde(rename = "btType", skip_serializing_if = "Option::is_none")]
    pub bt_type: Option<String>,
    #[serde(rename = "crossHighlightDataIfAny", skip_serializing_if = "Option::is_none")]
    pub cross_highlight_data_if_any: Option<Box<models::BtTableCrossHighlightData1753>>,
    #[serde(rename = "annotationId", skip_serializing_if = "Option::is_none")]
    pub annotation_id: Option<String>,
    #[serde(rename = "constraintId", skip_serializing_if = "Option::is_none")]
    pub constraint_id: Option<String>,
    #[serde(rename = "crossHighlightData", skip_serializing_if = "Option::is_none")]
    pub cross_highlight_data: Option<Box<models::BtTableCrossHighlightData1753>>,
    #[serde(rename = "featureId", skip_serializing_if = "Option::is_none")]
    pub feature_id: Option<String>,
    #[serde(rename = "parameterId", skip_serializing_if = "Option::is_none")]
    pub parameter_id: Option<String>,
    #[serde(rename = "partId", skip_serializing_if = "Option::is_none")]
    pub part_id: Option<String>,
    #[serde(rename = "precision", skip_serializing_if = "Option::is_none")]
    pub precision: Option<models::GbtTolerancePrecision>,
}

impl BtInspectionTableRowMetadata2485 {
    pub fn new() -> BtInspectionTableRowMetadata2485 {
        BtInspectionTableRowMetadata2485 {
            bt_type: None,
            cross_highlight_data_if_any: None,
            annotation_id: None,
            constraint_id: None,
            cross_highlight_data: None,
            feature_id: None,
            parameter_id: None,
            part_id: None,
            precision: None,
        }
    }
}

