/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtLazilyParsedFeatureScript {
    #[serde(rename = "checksum", skip_serializing_if = "Option::is_none")]
    pub checksum: Option<Box<models::BtuiFeatureStudioChecksum2438>>,
    #[serde(rename = "languageVersion", skip_serializing_if = "Option::is_none")]
    pub language_version: Option<i32>,
    #[serde(rename = "lines", skip_serializing_if = "Option::is_none")]
    pub lines: Option<serde_json::Value>,
    #[serde(rename = "model", skip_serializing_if = "Option::is_none")]
    pub model: Option<Box<models::BtmModel141>>,
    #[serde(rename = "module", skip_serializing_if = "Option::is_none")]
    pub module: Option<Box<models::BtpModule234>>,
    #[serde(rename = "moduleId", skip_serializing_if = "Option::is_none")]
    pub module_id: Option<Box<models::BtpModuleId235>>,
    #[serde(rename = "noticeModuleIds", skip_serializing_if = "Option::is_none")]
    pub notice_module_ids: Option<Box<models::BtpModuleId235>>,
    #[serde(rename = "parentLanguageVersion", skip_serializing_if = "Option::is_none")]
    pub parent_language_version: Option<i32>,
    #[serde(rename = "references", skip_serializing_if = "Option::is_none")]
    pub references: Option<std::collections::HashMap<String, models::BtMicroversionId366>>,
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<String>,
}

impl BtLazilyParsedFeatureScript {
    pub fn new() -> BtLazilyParsedFeatureScript {
        BtLazilyParsedFeatureScript {
            checksum: None,
            language_version: None,
            lines: None,
            model: None,
            module: None,
            module_id: None,
            notice_module_ids: None,
            parent_language_version: None,
            references: None,
            source: None,
        }
    }
}

