/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtOnePartProperties230 {
    #[serde(rename = "appearance", skip_serializing_if = "Option::is_none")]
    pub appearance: Option<Box<models::BtGraphicsAppearance1152>>,
    #[serde(rename = "appearanceForNewCell", skip_serializing_if = "Option::is_none")]
    pub appearance_for_new_cell: Option<Box<models::BtGraphicsAppearance1152>>,
    /// Type of JSON object.
    #[serde(rename = "btType", skip_serializing_if = "Option::is_none")]
    pub bt_type: Option<String>,
    #[serde(rename = "changedPropertiesSet", skip_serializing_if = "Option::is_none")]
    pub changed_properties_set: Option<Vec<String>>,
    #[serde(rename = "customProperties", skip_serializing_if = "Option::is_none")]
    pub custom_properties: Option<Box<models::BtPartCustomProperties1338>>,
    #[serde(rename = "material", skip_serializing_if = "Option::is_none")]
    pub material: Option<Box<models::BtPartMaterial1445>>,
    #[serde(rename = "materialForNewCell", skip_serializing_if = "Option::is_none")]
    pub material_for_new_cell: Option<Box<models::BtPartMaterial1445>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "nameForNewCell", skip_serializing_if = "Option::is_none")]
    pub name_for_new_cell: Option<String>,
    #[serde(rename = "nameIfNotNull", skip_serializing_if = "Option::is_none")]
    pub name_if_not_null: Option<Box<models::BtOnePartProperties230>>,
    #[serde(rename = "nodeId", skip_serializing_if = "Option::is_none")]
    pub node_id: Option<String>,
    #[serde(rename = "parsedQuery", skip_serializing_if = "Option::is_none")]
    pub parsed_query: Option<Box<models::BtpFunctionDeclaration246>>,
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<String>,
    #[serde(rename = "queryListParameter", skip_serializing_if = "Option::is_none")]
    pub query_list_parameter: Option<Box<models::BtmParameterQueryList148>>,
    #[serde(rename = "sheetMetalBendOrder", skip_serializing_if = "Option::is_none")]
    pub sheet_metal_bend_order: Option<Vec<String>>,
    #[serde(rename = "sheetMetalBendOrderIfNotNull", skip_serializing_if = "Option::is_none")]
    pub sheet_metal_bend_order_if_not_null: Option<Box<models::BtOnePartProperties230>>,
    #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<models::GbtPartVisibility>,
}

impl BtOnePartProperties230 {
    pub fn new() -> BtOnePartProperties230 {
        BtOnePartProperties230 {
            appearance: None,
            appearance_for_new_cell: None,
            bt_type: None,
            changed_properties_set: None,
            custom_properties: None,
            material: None,
            material_for_new_cell: None,
            name: None,
            name_for_new_cell: None,
            name_if_not_null: None,
            node_id: None,
            parsed_query: None,
            query: None,
            query_list_parameter: None,
            sheet_metal_bend_order: None,
            sheet_metal_bend_order_if_not_null: None,
            visibility: None,
        }
    }
}

