/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtParameterLookupTableListEntry1916 {
    #[serde(rename = "additionalLocalizedStrings", skip_serializing_if = "Option::is_none")]
    pub additional_localized_strings: Option<i32>,
    /// Type of JSON object.
    #[serde(rename = "btType", skip_serializing_if = "Option::is_none")]
    pub bt_type: Option<String>,
    #[serde(rename = "defaultIndex", skip_serializing_if = "Option::is_none")]
    pub default_index: Option<i32>,
    #[serde(rename = "displayName", skip_serializing_if = "Option::is_none")]
    pub display_name: Option<String>,
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<Vec<models::BtParameterLookupTableEntry1667>>,
    #[serde(rename = "label", skip_serializing_if = "Option::is_none")]
    pub label: Option<String>,
    #[serde(rename = "localizableName", skip_serializing_if = "Option::is_none")]
    pub localizable_name: Option<String>,
    #[serde(rename = "localizedLabel", skip_serializing_if = "Option::is_none")]
    pub localized_label: Option<String>,
    #[serde(rename = "localizedName", skip_serializing_if = "Option::is_none")]
    pub localized_name: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "stringsToLocalize", skip_serializing_if = "Option::is_none")]
    pub strings_to_localize: Option<Vec<String>>,
}

impl BtParameterLookupTableListEntry1916 {
    pub fn new() -> BtParameterLookupTableListEntry1916 {
        BtParameterLookupTableListEntry1916 {
            additional_localized_strings: None,
            bt_type: None,
            default_index: None,
            display_name: None,
            entries: None,
            label: None,
            localizable_name: None,
            localized_label: None,
            localized_name: None,
            name: None,
            strings_to_localize: None,
        }
    }
}

