/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtSingleAssemblyReferenceDisplayData1557 {
    /// Type of JSON object.
    #[serde(rename = "btType", skip_serializing_if = "Option::is_none")]
    pub bt_type: Option<String>,
    #[serde(rename = "contextWorkspaceId", skip_serializing_if = "Option::is_none")]
    pub context_workspace_id: Option<String>,
    #[serde(rename = "documentId", skip_serializing_if = "Option::is_none")]
    pub document_id: Option<String>,
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<models::GbtErrorStringEnum>,
    #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
    pub error_message: Option<String>,
    #[serde(rename = "fullElementId", skip_serializing_if = "Option::is_none")]
    pub full_element_id: Option<Box<models::BtFullElementId756>>,
    #[serde(rename = "isTransient", skip_serializing_if = "Option::is_none")]
    pub is_transient: Option<bool>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "referenceName", skip_serializing_if = "Option::is_none")]
    pub reference_name: Option<String>,
    #[serde(rename = "referenceNodeId", skip_serializing_if = "Option::is_none")]
    pub reference_node_id: Option<String>,
    #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
    pub visibility: Option<models::GbtbsFeatureVisibility>,
    #[serde(rename = "assemblyDisplayData", skip_serializing_if = "Option::is_none")]
    pub assembly_display_data: Option<Box<models::BtRootAssemblyDisplayData96>>,
    #[serde(rename = "hasConfiguration", skip_serializing_if = "Option::is_none")]
    pub has_configuration: Option<bool>,
    #[serde(rename = "occurrencesToExclude", skip_serializing_if = "Option::is_none")]
    pub occurrences_to_exclude: Option<Vec<models::BtOccurrence74>>,
    #[serde(rename = "transform", skip_serializing_if = "Option::is_none")]
    pub transform: Option<Box<models::BtbsMatrix386>>,
}

impl BtSingleAssemblyReferenceDisplayData1557 {
    pub fn new() -> BtSingleAssemblyReferenceDisplayData1557 {
        BtSingleAssemblyReferenceDisplayData1557 {
            bt_type: None,
            context_workspace_id: None,
            document_id: None,
            error: None,
            error_message: None,
            full_element_id: None,
            is_transient: None,
            name: None,
            reference_name: None,
            reference_node_id: None,
            visibility: None,
            assembly_display_data: None,
            has_configuration: None,
            occurrences_to_exclude: None,
            transform: None,
        }
    }
}

