/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtSketchSplineDisplayData359 {
    /// Type of JSON object.
    #[serde(rename = "btType", skip_serializing_if = "Option::is_none")]
    pub bt_type: Option<String>,
    #[serde(rename = "points", skip_serializing_if = "Option::is_none")]
    pub points: Option<Vec<f64>>,
    #[serde(rename = "closed", skip_serializing_if = "Option::is_none")]
    pub closed: Option<bool>,
    #[serde(rename = "controlPointCount", skip_serializing_if = "Option::is_none")]
    pub control_point_count: Option<i32>,
    #[serde(rename = "degree", skip_serializing_if = "Option::is_none")]
    pub degree: Option<i32>,
    #[serde(rename = "hasHandlesInSketch", skip_serializing_if = "Option::is_none")]
    pub has_handles_in_sketch: Option<bool>,
    #[serde(rename = "maximumParameter", skip_serializing_if = "Option::is_none")]
    pub maximum_parameter: Option<f64>,
    #[serde(rename = "minimumParameter", skip_serializing_if = "Option::is_none")]
    pub minimum_parameter: Option<f64>,
    #[serde(rename = "rational", skip_serializing_if = "Option::is_none")]
    pub rational: Option<bool>,
    #[serde(rename = "segment", skip_serializing_if = "Option::is_none")]
    pub segment: Option<bool>,
}

impl BtSketchSplineDisplayData359 {
    pub fn new() -> BtSketchSplineDisplayData359 {
        BtSketchSplineDisplayData359 {
            bt_type: None,
            points: None,
            closed: None,
            control_point_count: None,
            degree: None,
            has_handles_in_sketch: None,
            maximum_parameter: None,
            minimum_parameter: None,
            rational: None,
            segment: None,
        }
    }
}

