/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "btType")]
pub enum BtSingleReferenceDisplayData1943 {
    #[serde(rename="BTSingleAssemblyReferenceDisplayData-1557")]
    BtSingleAssemblyReferenceDisplayData1557 {
        #[serde(rename = "contextWorkspaceId", skip_serializing_if = "Option::is_none")]
        context_workspace_id: Option<String>,
        #[serde(rename = "documentId", skip_serializing_if = "Option::is_none")]
        document_id: Option<String>,
        #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
        error: Option<models::GbtErrorStringEnum>,
        #[serde(rename = "errorMessage", skip_serializing_if = "Option::is_none")]
        error_message: Option<String>,
        #[serde(rename = "fullElementId", skip_serializing_if = "Option::is_none")]
        full_element_id: Option<Box<models::BtFullElementId756>>,
        #[serde(rename = "isTransient", skip_serializing_if = "Option::is_none")]
        is_transient: Option<bool>,
        #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
        name: Option<String>,
        #[serde(rename = "referenceName", skip_serializing_if = "Option::is_none")]
        reference_name: Option<String>,
        #[serde(rename = "referenceNodeId", skip_serializing_if = "Option::is_none")]
        reference_node_id: Option<String>,
        #[serde(rename = "visibility", skip_serializing_if = "Option::is_none")]
        visibility: Option<models::GbtbsFeatureVisibility>,
    },
}

impl Default for BtSingleReferenceDisplayData1943 {
    fn default() -> Self {
        Self::BtSingleAssemblyReferenceDisplayData1557 {
            context_workspace_id: Default::default(),
            document_id: Default::default(),
            error: Default::default(),
            error_message: Default::default(),
            full_element_id: Default::default(),
            is_transient: Default::default(),
            name: Default::default(),
            reference_name: Default::default(),
            reference_node_id: Default::default(),
            visibility: Default::default(),
        }
        
    }
}


