/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(tag = "btType")]
pub enum BtfsValue1888 {
    #[serde(rename="BTFSValueArray-1499")]
    BtfsValueArray1499 {
        #[serde(rename = "typeTag", skip_serializing_if = "Option::is_none")]
        type_tag: Option<String>,
    },
    #[serde(rename="BTFSValueBoolean-1195")]
    BtfsValueBoolean1195 {
        #[serde(rename = "typeTag", skip_serializing_if = "Option::is_none")]
        type_tag: Option<String>,
    },
    #[serde(rename="BTFSValueMap-2062")]
    BtfsValueMap2062 {
        #[serde(rename = "typeTag", skip_serializing_if = "Option::is_none")]
        type_tag: Option<String>,
    },
    #[serde(rename="BTFSValueNumber-772")]
    BtfsValueNumber772 {
        #[serde(rename = "typeTag", skip_serializing_if = "Option::is_none")]
        type_tag: Option<String>,
    },
    #[serde(rename="BTFSValueOther-1124")]
    BtfsValueOther1124 {
        #[serde(rename = "typeTag", skip_serializing_if = "Option::is_none")]
        type_tag: Option<String>,
    },
    #[serde(rename="BTFSValueString-1422")]
    BtfsValueString1422 {
        #[serde(rename = "typeTag", skip_serializing_if = "Option::is_none")]
        type_tag: Option<String>,
    },
    #[serde(rename="BTFSValueTooBig-1247")]
    BtfsValueTooBig1247 {
        #[serde(rename = "typeTag", skip_serializing_if = "Option::is_none")]
        type_tag: Option<String>,
    },
    #[serde(rename="BTFSValueUndefined-2003")]
    BtfsValueUndefined2003 {
        #[serde(rename = "typeTag", skip_serializing_if = "Option::is_none")]
        type_tag: Option<String>,
    },
    #[serde(rename="BTFSValueWithUnits-1817")]
    BtfsValueWithUnits1817 {
        #[serde(rename = "typeTag", skip_serializing_if = "Option::is_none")]
        type_tag: Option<String>,
    },
}

impl Default for BtfsValue1888 {
    fn default() -> Self {
        Self::BtfsValueArray1499 {
            type_tag: Default::default(),
        }
        
    }
}


