/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BtmInferenceQueryWithOccurrence1083 {
    /// Type of JSON object.
    #[serde(rename = "btType", skip_serializing_if = "Option::is_none")]
    pub bt_type: Option<String>,
    /// Microversion that resulted from the import.
    #[serde(rename = "importMicroversion", skip_serializing_if = "Option::is_none")]
    pub import_microversion: Option<String>,
    #[serde(rename = "nodeId", skip_serializing_if = "Option::is_none")]
    pub node_id: Option<String>,
    #[serde(rename = "deterministicIdList", skip_serializing_if = "Option::is_none")]
    pub deterministic_id_list: Option<Box<models::BtmIndividualQueryBase139>>,
    #[serde(rename = "deterministicIds", skip_serializing_if = "Option::is_none")]
    pub deterministic_ids: Option<Vec<String>>,
    #[serde(rename = "generateSectionEntityQuery", skip_serializing_if = "Option::is_none")]
    pub generate_section_entity_query: Option<bool>,
    #[serde(rename = "generatedSectionQueryId", skip_serializing_if = "Option::is_none")]
    pub generated_section_query_id: Option<String>,
    #[serde(rename = "query", skip_serializing_if = "Option::is_none")]
    pub query: Option<Box<models::BtmIndividualQueryBase139>>,
    #[serde(rename = "queryString", skip_serializing_if = "Option::is_none")]
    pub query_string: Option<String>,
    #[serde(rename = "fullPathAsString", skip_serializing_if = "Option::is_none")]
    pub full_path_as_string: Option<String>,
    #[serde(rename = "occurrence", skip_serializing_if = "Option::is_none")]
    pub occurrence: Option<Box<models::BtOccurrence74>>,
    #[serde(rename = "path", skip_serializing_if = "Option::is_none")]
    pub path: Option<Vec<String>>,
    #[serde(rename = "entityQuery", skip_serializing_if = "Option::is_none")]
    pub entity_query: Option<String>,
    #[serde(rename = "inferenceType", skip_serializing_if = "Option::is_none")]
    pub inference_type: Option<models::GbtEntityInferenceType>,
    #[serde(rename = "secondDeterministicId", skip_serializing_if = "Option::is_none")]
    pub second_deterministic_id: Option<String>,
    #[serde(rename = "secondEntityQuery", skip_serializing_if = "Option::is_none")]
    pub second_entity_query: Option<String>,
}

impl BtmInferenceQueryWithOccurrence1083 {
    pub fn new() -> BtmInferenceQueryWithOccurrence1083 {
        BtmInferenceQueryWithOccurrence1083 {
            bt_type: None,
            import_microversion: None,
            node_id: None,
            deterministic_id_list: None,
            deterministic_ids: None,
            generate_section_entity_query: None,
            generated_section_query_id: None,
            query: None,
            query_string: None,
            full_path_as_string: None,
            occurrence: None,
            path: None,
            entity_query: None,
            inference_type: None,
            second_deterministic_id: None,
            second_entity_query: None,
        }
    }
}

