/*
 * Onshape REST API
 *
 * ## Welcome to the Onshape REST API Explorer  To use this API explorer, sign in to your [Onshape](https://cad.onshape.com) account in another tab, then click the **Try it out** button below (it toggles to a **Cancel** button when selected).  See the **[API Explorer Guide](https://onshape-public.github.io/docs/api-intro/explorer/)** for help navigating this API Explorer, including **[authentication](https://onshape-public.github.io/docs/api-intro/explorer/#authentication)**.  **Tip:** To ensure the current session isn't used when trying other authentication techniques, make sure to [remove the Onshape cookie](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site) as per the instructions for your browser. Alternatively, you can use a private or incognito window.  ## See Also  * [Onshape API Guide](https://onshape-public.github.io/docs/): Our full suite of developer guides, to be used as an accompaniment to this API Explorer. * [Onshape Developer Portal](https://cad.onshape.com/appstore/dev-portal): The Onshape portal for managing your API keys, OAuth2 credentials, your Onshape applications, and your Onshape App Store entries. * [Authentication Guide](https://onshape-public.github.io/docs/auth/): Our guide to using API keys, request signatures, and OAuth2 in  your Onshape applications.
 *
 * The version of the OpenAPI document: 1.198.56658-8969b956ea73
 * Contact: api-support@onshape.zendesk.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum GbtWeldType {
    #[serde(rename = "NONE")]
    None,
    #[serde(rename = "SQUARE_GROOVE")]
    SquareGroove,
    #[serde(rename = "V_GROOVE")]
    VGroove,
    #[serde(rename = "U_GROOVE")]
    UGroove,
    #[serde(rename = "J_GROOVE")]
    JGroove,
    #[serde(rename = "BEVEL_GROOVE")]
    BevelGroove,
    #[serde(rename = "SINGLE_BEVEL_BUTT_BROAD_ROOT")]
    SingleBevelButtBroadRoot,
    #[serde(rename = "V_FLARE_GROOVE")]
    VFlareGroove,
    #[serde(rename = "BEVEL_FLARE_GROOVE")]
    BevelFlareGroove,
    #[serde(rename = "BEAD_JOINT")]
    BeadJoint,
    #[serde(rename = "FILLET_JOINT")]
    FilletJoint,
    #[serde(rename = "UNKNOWN")]
    Unknown,

}

impl std::fmt::Display for GbtWeldType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "NONE"),
            Self::SquareGroove => write!(f, "SQUARE_GROOVE"),
            Self::VGroove => write!(f, "V_GROOVE"),
            Self::UGroove => write!(f, "U_GROOVE"),
            Self::JGroove => write!(f, "J_GROOVE"),
            Self::BevelGroove => write!(f, "BEVEL_GROOVE"),
            Self::SingleBevelButtBroadRoot => write!(f, "SINGLE_BEVEL_BUTT_BROAD_ROOT"),
            Self::VFlareGroove => write!(f, "V_FLARE_GROOVE"),
            Self::BevelFlareGroove => write!(f, "BEVEL_FLARE_GROOVE"),
            Self::BeadJoint => write!(f, "BEAD_JOINT"),
            Self::FilletJoint => write!(f, "FILLET_JOINT"),
            Self::Unknown => write!(f, "UNKNOWN"),
        }
    }
}

impl Default for GbtWeldType {
    fn default() -> GbtWeldType {
        Self::None
    }
}

